### ISSUE TITLE
E/FMAuthPlugin(21695): The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.

### ISSUE THREAD

**Issue by KenZync** [BritehouseMobile/flutter-microsoft-authentication#7]
I made changes from example it's fine but when I try to recreate new flutter app it doesn't work
How do i debug or fix this

**Comment by lvsecoto** [comment]
You should rester your app [hear](https://apps.dev.microsoft.com/?referrer=https%3A%2F%2Fdev.onedrive.com).

And submit the package name and signature hash of your app.

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/app-registration?view=odsp-graph-online
